[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
follow_imports = "silent"
ignore_missing_imports = true
strict_optional = true
check_untyped_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
namespace_packages = true
plugins = "sqlalchemy.ext.mypy.plugin"

# Use .gitignore for exclusions
exclude = ".*/\\.*"

[[tool.mypy.overrides]]
module = "sqlalchemy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.sqlalchemy]
mypy_enable_sqlalchemy_plugin = true
