version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - minio

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data

volumes:
  minio-data:
